name: namer_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.9.0
  table_calendar: 3.2.0
  intl: 0.20.2
  http: ^1.4.0
  flutter_local_notifications: ^19.2.1
  dotenv: ^4.2.0
  tray_manager: ^0.5.0
  uuid: ^4.5.1
  go_router: ^16.0.0
  window_manager: ^0.5.0
  record: 6.0.0
  json_annotation: ^4.9.0
  flutter_colorpicker: ^1.1.0
  rrule: ^0.2.17
  http_parser: ^4.1.2
  ffmpeg_kit_flutter: ^6.0.3
  pasteboard: ^0.4.0
  image: ^4.5.4
  supabase_auth_ui: ^0.5.5
  app_links: ^6.4.1
  win32_registry: ^2.1.0
  timezone: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.3.3
  json_serializable: ^6.8.0
  msix: ^3.16.12

flutter:
  uses-material-design: true

msix_config:
  display_name: Calendai
  identity_name: calendai.app
  msix_version: 1.0.0.0
  logo_path: C:\path\to\logo.png
  protocol_activation: calendai
  capabilities: internetClient, location, microphone, webcam
